name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code from repository
        uses: actions/checkout@v3

      - name: Set up Java JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Compile and package with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Docker Hub authentication
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for the app with labels
        run: |
          docker buildx build -t sekula8/app:latest \
            --label build_date=$(date) \
            --label commit_hash=${GITHUB_SHA} \
            ./DevOps_Project-master  

      - name: Display Docker image tag and build info
        run: |
          echo "Built Docker image: sekula8/app:latest with commit hash $GITHUB_SHA and build date $(date)"

      - name: Upload Docker image to Docker Hub
        run: |
          docker push sekula8/app:latest
